configMapGenerator:
- files:
  - application.yml
  name: 82022282-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: cepgbaseacr.azurecr.io/82022282
  newTag: "202409090535"